### ISSUE TITLE
Choice Actor Panics

### ISSUE THREAD

**Issue by degregat** [degregat/stateright-experiments#1]
Here is the debug log of the example from the first commit (77b6b34ac00c10239c7fd8e193bd278ee3f67c23).

> RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/stateright-experiments`
Example: Advance Choice Actor State by Hand
SupervisorMachine initializing.
CounterActor initializing.
SupervisorMachine initializing.
CounterActor initializing.
{"always_true": Path([(ActorModelState { actor_states: [SupervisorState { addr: Id(0), threshold: 3, counter_addr: Id(1), success: false }, CounterState { addr: Id(1), counter: 0 }], history: 0, is_timer_set: [Timers({}), Timers({})], network: UnorderedDuplicating({}) }, None)])}
checker init done
advance checker state: start
SupervisorMachine initializing.
CounterActor initializing.
CounterActor on_msg.
CounterMachine response.
CounterActor on_msg done.
advance checker state: done
Example: Assert Discovery
SupervisorMachine initializing.
CounterActor initializing.
SupervisorMachine initializing.
CounterActor initializing.
{"always_true": Path([(ActorModelState { actor_states: [SupervisorState { addr: Id(0), threshold: 3, counter_addr: Id(1), success: false }, CounterState { addr: Id(1), counter: 0 }], history: 0, is_timer_set: [Timers({}), Timers({})], network: UnorderedDuplicating({}) }, None)])}
checker init done
checker assert discovery
SupervisorMachine initializing.
CounterActor initializing.
SupervisorMachine initializing.
CounterActor initializing.
SupervisorMachine initializing.
CounterActor initializing.
thread 'main' panicked at 'Invalid discovery for "always_true", but a valid one was found. found=[]', .../.cargo/registry/src/github.com-1ecc6299db9ec823/stateright-0.30.0/src/checker.rs:530:9
stack backtrace:
   0:        0x1030a0d80 - std::backtrace_rs::backtrace::libunwind::trace::h2000fb4d08dbcc59
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1030a0d80 - std::backtrace_rs::backtrace::trace_unsynchronized::h2b5e61495350674d
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1030a0d80 - std::sys_common::backtrace::_print_fmt::h05f5bfbdb3415936
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x1030a0d80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h105074e3d85f800b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1030b3994 - core::fmt::write::h34766cf8fff7af1e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:        0x10309ed0c - std::io::Write::write_fmt::hd64c4cf6e7adea59
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:        0x1030a0b94 - std::sys_common::backtrace::_print::hd92783a665d3ebfb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x1030a0b94 - std::sys_common::backtrace::print::h2a6828a537036cf9
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x1030a2270 - std::panicking::default_hook::{{closure}}::h4e82ce6ccef941b2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:        0x1030a1fc8 - std::panicking::default_hook::h29f62f8795c5cb00
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:        0x1030a2780 - std::panicking::rust_panic_with_hook::h19862cbd0fbda7ba
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:        0x1030a26b4 - std::panicking::begin_panic_handler::{{closure}}::h3f3626935e1669fe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:        0x1030a11a0 - std::sys_common::backtrace::__rust_end_short_backtrace::h5054ef52bd507d0a
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:        0x1030a2410 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:        0x1030be2fc - core::panicking::panic_fmt::h7e47e10600a90221
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:        0x102ffdb3c - stateright::checker::Checker::assert_discovery::h4b616f62365ab1e6
                               at .../.cargo/registry/src/github.com-1ecc6299db9ec823/stateright-0.30.0/src/checker.rs:530:9
  16:        0x103023460 - stateright-experiments::check_counter_supervisor_by_discovery::hffa1f055de82bd7d
                               at .../src/main.rs:108:5
  17:        0x103022be0 - stateright-experiments::main::h95608d9d279cbad0
                               at .../src/main.rs:18:5
  18:        0x103001b8c - core::ops::function::FnOnce::call_once::h831a8500b76f5104
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
  19:        0x10300a4bc - std::sys_common::backtrace::__rust_begin_short_backtrace::hf5735b780d6391c5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:134:18
  20:        0x102ff64dc - std::rt::lang_start::{{closure}}::h998ba42efae55541
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:166:18
  21:        0x10309c654 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf2f6b444963da11f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
  22:        0x10309c654 - std::panicking::try::do_call::h9152231fddd58858
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  23:        0x10309c654 - std::panicking::try::hcc27eab3b8ee3cb1
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  24:        0x10309c654 - std::panic::catch_unwind::hca546a4311ab9871
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  25:        0x10309c654 - std::rt::lang_start_internal::{{closure}}::h4e65aa71fe685c85
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
  26:        0x10309c654 - std::panicking::try::do_call::h61aea55fbdf97fc2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  27:        0x10309c654 - std::panicking::try::hcfc3b62fb8f6215e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  28:        0x10309c654 - std::panic::catch_unwind::h61a201e98b56a743
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  29:        0x10309c654 - std::rt::lang_start_internal::h91996717d3eb1d2a
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  30:        0x102ff64a8 - std::rt::lang_start::hf46514a551293195
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:165:17
  31:        0x10302447c - _main

**Comment by degregat** [comment]
A third actor to simulate user input was missing, since messages always need to come from an actor.
